#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Zer01TI'
        hostname: z1tsp01dt10
        username: zer01ti
        password: '$6$3Ij9QIZwY2Vvq4I7$o/B8i4eODNtUGDh2BhA65W7E1J/L7PJv5Lf0OPNrIpFkxHcjDrt33VzL3t8oxEaI9LRg5GTaMLKdvuUPyG.Q5.'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    storage:
    layout:
      name: lvm
      sizing-policy: all
    packages:
        - vlc
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
